services:
  greenwichbooth:
    build: .
    container_name: greenwichbooth
    ports:
      - "9080:80"
    restart: unless-stopped
    depends_on:
      - greenwichbooth-api
    networks:
      - booth

  greenwichbooth-api:
    build: ./api
    container_name: greenwichbooth-api
    restart: unless-stopped
    volumes:
      - booth_photos:/tmp/photos
    networks:
      - booth

networks:
  booth:

volumes:
  booth_photos:
