server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location /upload {
    proxy_pass http://greenwichbooth-api:3001/upload;
    client_max_body_size 15m;
    proxy_set_header Host $host;
  }

  location /dl/ {
    proxy_pass http://greenwichbooth-api:3001;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
  }
}
